-- MySQL Script generated by MySQL Workbench
-- Tue Jun  1 11:36:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LineaProyectoFinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LineaProyectoFinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LineaProyectoFinal` DEFAULT CHARACTER SET utf8 ;
USE `LineaProyectoFinal` ;

-- -----------------------------------------------------
-- Table `LineaProyectoFinal`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LineaProyectoFinal`.`Usuarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LineaProyectoFinal`.`preguntasuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LineaProyectoFinal`.`preguntasuser` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pregunta1` VARCHAR(45) NOT NULL,
  `respuesta1` VARCHAR(45) NOT NULL,
  `pregunta2` VARCHAR(45) NOT NULL,
  `respuesta2` VARCHAR(45) NOT NULL,
  `pregunta3` VARCHAR(45) NOT NULL,
  `respuesta3` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
